### ISSUE TITLE
Search result is not returned for some terms with Contains search 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/drug-dictionary-app#70]
### Issue description
*Description of the issue*
On performing search using "len" and then selecting "anti-CD22 scFv TCRz:41BB-CAR lentiviral vector-transduced autologous T lymphocytes" from the autosuggest using a contains search on react-dev, when we select and submit this term, we do not get any search result. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Select the "Contains" radio button on https://react-app-dev.cancer.gov/drug-dictionary-app/pr-68 
2. Type "len" and then select the term "anti-CD22 scFv TCRz:41BB-CAR lentiviral vector-transduced autologous T lymphocytes" from the autosuggest drop-down
3. Click the Search button.
4. No search result is returned.

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/96515151-d0762300-1232-11eb-986b-c6c40bb2fa64.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
@alinai There are steps missing.  At what point in the sequence do you select the "Contains" button?

Do not answer here.  Please update the ticket.

**Comment by alinai** [comment]
The ticket has been updated!

**Comment by kate-mashkina** [comment]
Digging more into this issue:
_Example where contains does not return anything_
1.Select contains
2. type 'can' and select '**allogeneic large multivalent immunogen breast cancer vaccine**' (this term does not have any special characters
3. hit search and see 'No results found'

Now, if switched back to 'starts with' it will spit out result, which is an exact term. 

Example where contains returns one result
1.Select contains
2. type 'glo' and select '**horse anti-thymocyte globulin**' 
3. hit search and see the term is returned

**Comment by blairlearn** [comment]
This occurs because the ES mapping document imposes a limit of 30 characters on the `ngram_filter` which is used for `contains` searches.

**Solution 1:** Increase the `ngram_max` value to accommodate longer names. The current maximum term name size is 685 characters. Setting `ngram_filter` to allow that would increase the size of the index from 71 MB to 510, so that's not  a good solution.

**Solution two:** Adjust the `ngram_filter` to use a larger `max_gram` value.  (Tentatively, 100 characters.)  If the user enters a string longer than that, do a search based on the first X number of characters.  Ideally, this would only apply to contains search as begins is not affected by this issue.  (This value would need to be configurable, but with a default so we don't have to remember to configure it for the deployment.)

**Solution three:** Adjust the elasticsearch to return any exact matches which would match the autosuggest's query. This would fix the issue for the specific case of a term selected from autosuggest, but would fail for anything longer than the `max_gram` value which was  not an exact match.

After discussion with @blairlearn, @VictoriaSunNIH, @zhuomingao, @blilianyu, and @mworrest, the decision was to go with solution #2.
